name: Monitor Nginx & Backup To S3

on:
  schedule:
    - cron: '*/30 * * * *' 
    - cron: '0 0 * * *'    

jobs:
  monitor:
    runs-on: self-hosted
    steps:
      - name: Cek Status Nginx
        id: check_nginx
        run: |
          if ! systemctl is-active --quiet nginx; then
            echo "Nginx tidak aktif! Melakukan restart..."
            sudo systemctl restart nginx
            echo "Nginx telah di-restart."
            echo "::set-output name=status::restarted"
          else
            echo "Nginx berjalan normal."
            echo "::set-output name=status::running"
          fi

      - name: Notifikasi Hasil Cek
        run: |
          if [ "${{ steps.check_nginx.outputs.status }}" == "restarted" ]; then
            echo "Nginx telah di-restart. Status: ${ { steps.check_nginx.outputs.status }}."
          else
            echo "Nginx berjalan normal. Status: ${ { steps.check_nginx.outputs.status }}."
          fi

      - name: Cek Log Kesalahan Jika Nginx Tidak Bisa Dijalankan
        if: steps.check_nginx.outputs.status == 'restarted'
        run: |
          if ! systemctl is-active --quiet nginx; then
            echo "Nginx masih tidak aktif! Memeriksa log kesalahan..."
            sudo tail -n 10 /var/log/nginx/error.log
          fi

  backup:
    runs-on: self-hosted
    steps:
      - name: Sinkronkan Direktori ke S3
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync /etc/nginx s3://docker-actions/monba_nginx --delete
